Vagrant.configure("2") do |config|
if Vagrant.has_plugin?("vagrant-hostmanager")
     config.hostmanager.enabled = true
     config.hostmanager.manage_host = true
     config.hostmanager.ignore_private_ip = false
     config.hostmanager.include_offline = true
end
config.vm.define "win7-1" do |config|
  config.vm.box = "d1vious/windows_7"
  config.vm.box_version = "1.0"
  config.vm.hostname = "win7-1"
  config.vm.boot_timeout = 600
  config.vm.communicator = "winrm"
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 300
  config.winrm.retry_limit = 20
  #config.vm.network "forwarded_port", guest: 5985, host: 5988
  config.vm.network :private_network, ip: "10.0.1.55"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        #ansible_port: 5988,
        hostname: config.vm.hostname
      }
      ansible.playbook = "../../ansible/#{config.vm.hostname}.yml"
      ansible.config_file = "../../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{config.vm.hostname}"
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end
end