config.vm.define "win10-1" do |config|
  config.vm.box = "gusztavvargadr/windows-10-enterprise"
  config.vm.box_version = "2101.0.2106"
  config.vm.hostname = "win10-1"
  config.vm.boot_timeout = 600
  config.vm.communicator = "winrm"
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 300
  config.winrm.retry_limit = 20
  config.vm.network "forwarded_port", guest: 5985, host: 5985
  config.vm.network :private_network, ip: "{{ windows_client_private_ip_1 }}"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        ansible_port: 5985,
        ansible_winrm_scheme: 'http',
        splunk_server: "{{ splunk_server }}",
        splunk_indexer_ip: "{{ splunk_server_private_ip }}",
        caldera_server_ip: '{{ caldera_server_private_ip }}',
        win_password: '{{ win_password }}',
        splunk_uf_win_url: '{{ splunk_uf_win_url }}',
        nxlog_url: '{{ nxlog_url }}',
        install_dsp: '{{ install_dsp }}',
        win_sysmon_url: '{{ win_sysmon_url }}',
        win_sysmon_template: '{{ win_sysmon_template }}',
        splunk_admin_password: '{{ splunk_admin_password }}',
        windows_server_join_domain: '{{ windows_client_join_domain }}',
        windows_domain_controller_private_ip: '{{ windows_domain_controller_private_ip }}',
        run_demo: '{{ run_demo }}',
        demo_scenario: '{{ demo_scenario }}',
        capture_attack_data: '{{ capture_attack_data }}',
        win_timezone: '{{ win_timezone }}',
        domain_name: '{{ domain_name }}',
        win_domain_admin: '{{ win_domain_admin }}',
        local_admin_password: '{{ local_admin_password }}',
        hostname: config.vm.hostname
      }
      ansible.playbook = "../ansible/#{config.vm.hostname}.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{config.vm.hostname}"
    vb.customize ["modifyvm", :id, "--memory", {{ windows_client_memory }}]
    vb.customize ["modifyvm", :id, "--cpus", {{ windows_client_cpus }}]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end

config.vm.define "win10-2" do |config|
  config.vm.box = "StefanScherer/windows_10"
  config.vm.box_version = "2021.08.17"
  config.vm.hostname = "win10-2"
  config.vm.boot_timeout = 600
  config.vm.communicator = "winrm"
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 300
  config.winrm.retry_limit = 20
  config.vm.network "forwarded_port", guest: 5985, host: 5987
  config.vm.network :private_network, ip: "{{ windows_client_private_ip_2 }}"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        ansible_port: 5987,
        ansible_winrm_scheme: 'http',
        splunk_server: "{{ splunk_server }}",
        splunk_indexer_ip: "{{ splunk_server_private_ip }}",
        caldera_server_ip: '{{ caldera_server_private_ip }}',
        win_password: '{{ win_password }}',
        splunk_uf_win_url: '{{ splunk_uf_win_url }}',
        nxlog_url: '{{ nxlog_url }}',
        install_dsp: '{{ install_dsp }}',
        win_sysmon_url: '{{ win_sysmon_url }}',
        win_sysmon_template: '{{ win_sysmon_template }}',
        splunk_admin_password: '{{ splunk_admin_password }}',
        windows_server_join_domain: '{{ windows_client_join_domain }}',
        windows_domain_controller_private_ip: '{{ windows_domain_controller_private_ip }}',
        run_demo: '{{ run_demo }}',
        demo_scenario: '{{ demo_scenario }}',
        capture_attack_data: '{{ capture_attack_data }}',
        win_timezone: '{{ win_timezone }}',
        domain_name: '{{ domain_name }}',
        win_domain_admin: '{{ win_domain_admin }}',
        local_admin_password: '{{ local_admin_password }}',
        hostname: config.vm.hostname
      }
      ansible.playbook = "../ansible/#{config.vm.hostname}.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{config.vm.hostname}"
    vb.customize ["modifyvm", :id, "--memory", {{ windows_client_memory }}]
    vb.customize ["modifyvm", :id, "--cpus", {{ windows_client_cpus }}]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end

config.vm.define "win10-dev" do |config|
  #config.vm.box = "gusztavvargadr/visual-studio"
  #config.vm.box_version = "2019.0.2012"
  config.vm.box = "gusztavvargadr/windows-10-enterprise"
  config.vm.box_version = "2101.0.2106"
  config.vm.hostname = "win10-dev"
  config.vm.boot_timeout = 600
  config.vm.communicator = "winrm"
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 300
  config.winrm.retry_limit = 20
  config.vm.network "forwarded_port", guest: 5985, host: 5988
  config.vm.network :private_network, ip: "{{ windows_client_private_ip_dev }}"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        ansible_port: 5988,
        ansible_winrm_scheme: 'http',
        splunk_server: "{{ splunk_server }}",
        splunk_indexer_ip: "{{ splunk_server_private_ip }}",
        caldera_server_ip: '{{ caldera_server_private_ip }}',
        win_password: '{{ win_password }}',
        splunk_uf_win_url: '{{ splunk_uf_win_url }}',
        nxlog_url: '{{ nxlog_url }}',
        install_dsp: '{{ install_dsp }}',
        win_sysmon_url: '{{ win_sysmon_url }}',
        win_sysmon_template: '{{ win_sysmon_template }}',
        splunk_admin_password: '{{ splunk_admin_password }}',
        windows_server_join_domain: '{{ windows_client_join_domain }}',
        windows_domain_controller_private_ip: '{{ windows_domain_controller_private_ip }}',
        run_demo: '{{ run_demo }}',
        demo_scenario: '{{ demo_scenario }}',
        capture_attack_data: '{{ capture_attack_data }}',
        win_timezone: '{{ win_timezone }}',
        domain_name: '{{ domain_name }}',
        win_domain_admin: '{{ win_domain_admin }}',
        local_admin_password: '{{ local_admin_password }}',
        hostname: config.vm.hostname
      }
      ansible.playbook = "../ansible/#{config.vm.hostname}.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{config.vm.hostname}"
    vb.customize ["modifyvm", :id, "--memory", {{ windows_client_memory_dev }}]
    vb.customize ["modifyvm", :id, "--cpus", {{ windows_client_cpus_dev }}]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end
