---
- name: Change dns server to domain controller
  win_dns_client:
    adapter_names: "{{ ansible_interfaces.1.connection_name }}"
    ipv4_addresses: "{{ windows_domain_controller_private_ip }}"

- name: reboot | Rebooting after setting DNS server
  win_reboot:

- name: Join domain
  win_domain_membership:
    dns_domain_name: "{{ root_domain }}"
    hostname: "{{ hostname }}"
    domain_admin_user: "{{ win_domain_admin }}@{{ root_domain }}"
    domain_admin_password: "{{ win_password }}"
    state: "domain"
  register: domain_state

- name: reboot | Reboot after joining domain
  win_reboot:
    msg: "Rebooting after joining domain"
  when: domain_state.reboot_required
